### ISSUE TITLE
is it possible to share a built artifact?

### ISSUE THREAD

**Issue by jobez** [rogerallen/WinGridStrument#6]
i am eager to try this project out! thank you for sharing

there seems to be an expiry point to the https://ci.appveyor.com/project/rogerallen/wingridstrument/build/artifacts url preserving artifacts. im having a bit of a time building this project locally* and was wondering if you could maybe share a build. would be much appreciated!

*(fluidsynth installed by vcpkg isnt being recognized by vscode, i barely dev on windows so all this stuff is irritating malarkey right now [and yes i did do that step from `vcpkg integrate install`])

**Comment by jobez** [comment]
It occurred to me I could clone this project and initiate the CI myself https://ci.appveyor.com/project/jobez/wingridstrument lets see if that will do it! thanks again for sharing, am excited to give it a whirl 👯‍♂️

**Comment by rogerallen** [comment]
Glad you figured it out.  Hope it works out for you.

**Comment by rogerallen** [comment]
Please let me know if you have any feedback @jobez -- good or bad.  I haven't gotten any feedback from others trying this out.
